int WORLD_COLS = 2;
int WORLD_ROWS = 2;
int TILE_SIZE_PIXELS = 32;

char WORLD_FILE_NAME_TO_SAVE[255] = ".txt";

int NUMBER_OF_ISLANDS = 0;

int WORLD_CURRENT_TYPE = 0;
int WORLD_CURRENT_INDEX = 0;
