int ISLANDS_WORLD_COLS = 2;
int ISLANDS_WORLD_ROWS = 2;
int ISLANDS_TILE_SIZE_PIXELS = 32;

char ISLANDS_WORLD_FILE_NAME_TO_SAVE[255] = ".txt";

int ISLANDS_NUMBER_OF_ISLANDS = 0;

int ISLANDS_WORLD_CURRENT_TYPE = 0;
int ISLANDS_WORLD_CURRENT_INDEX = 0;
